x-deploy-config: &default-deploy-config
  deploy:
    resources:
      limits:
        memory: 128M
        cpus: '0.50'
      reservations:
        memory: 100M
        cpus: '0.25'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "9000:9000"
      - "5173:5173"
    environment:
      TZ: America/Sao_Paulo
    networks:
      - enterprise_network
    extra_hosts: 
      - "host.docker.internal:host-gateway"
    command: php-fpm
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.50'
        reservations:
          memory: 100M
          cpus: '0.25'
  
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    environment:
      TZ: America/Sao_Paulo
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - enterprise_network
    depends_on:
      - php
    <<: *default-deploy-config

  mysql:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - enterprise_network
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: enterprise_ead
      MYSQL_USER: enterprise_ead
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
    deploy:
      resources:
        limits:
          memory: 500M
          cpus: '1'
        reservations:
          memory: 256M
          cpus: '0.5'

volumes:
  mysql_data:

networks:
  enterprise_network:
    driver: bridge